FROM gradle:8.0.1-jdk17 AS builder
COPY ./stubs /app
WORKDIR /app
RUN curl -L "https://search.maven.org/remotecontent?filepath=io/github/azagniotov/stubby4j/7.5.2/stubby4j-7.5.2.jar" -o /app/stubby4j.jar

FROM openjdk:17-jdk-slim-buster
LABEL app=Heartbeat
LABEL arch=stubs
WORKDIR /app
EXPOSE 4323
COPY --from=builder /app /app
CMD ["java", "-jar", "stubby4j.jar", "-d", "stubs.yaml", "-l", "0.0.0.0", "-s", "4323"]
