FROM node:16-alpine AS builder
WORKDIR /app
COPY ./backend ./
RUN yarn install && yarn build

FROM ubuntu:latest
LABEL app=HeartBeat
LABEL arch=Backend
RUN mkdir -p ./csv
EXPOSE 3001
ENTRYPOINT [ "yarn", "host" ]