FROM node:16-alpine as builder
COPY ./frontend /app
WORKDIR /app
RUN npm install -g pnpm
RUN pnpm install && pnpm build

FROM nginx:latest
LABEL app=HeartBeat
LABEL arch=Frontend
WORKDIR /app
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./infra/nginx.conf /etc/nginx/nginx.conf
