#!/bin/bash

AwsHost=${AWSHost}
AwsAccountId=${AWSAccountId}
SshPublicKey=${SSHPublicKey}

aws --region cn-north-1 cloudformation update-stack --stack-name Heartbeat --template-body file://infra/cloudformation.yml --parameters ParameterKey=GitHubOrg,ParameterValue=au-heartbeat ParameterKey=RepositoryName,ParameterValue=Heartbeat ParameterKey=AwsHost,ParameterValue=${AwsHost} ParameterKey=AwsAccountId,ParameterValue=${AwsAccountId}  ParameterKey=SSHPublicKey,ParameterValue="${SshPublicKey}" --capabilities CAPABILITY_NAMED_IAM
