#!/bin/bash

run_backend_check() {
  cd backend
  ./gradlew clean check
  ./gradlew clean build
  bash <(curl -Ls https://coverage.codacy.com/get.sh)
}

run_frontend_check(){
  cd frontend
  pnpm install --no-frozen-lockfile
  pnpm lint
  pnpm coverage
  pnpm build
  bash <(curl -Ls https://coverage.codacy.com/get.sh)
}

set -e
set +x

if [[ "$1" == "backend" ]]; then
  run_backend_check
elif [[ "$1" == "frontend" ]]; then
  run_frontend_check
else
  echo "Invalid command: $1"
  exit 1
fi