#!/bin/bash
set -e
set +x

display_help() {
    # taken from https://stackoverflow.com/users/4307337/vincent-stans
    echo "Usage: $0 {security|frontend|backend|backend-license|frontend-license}" >&2
    echo
    echo "   frontend           run check for the frontend"
    echo "   backend            run check for the backend"
    echo
    exit 1
}

run_backend_check() {
  cd backend
  ./gradlew clean check
  ./gradlew clean build
  bash <(curl -Ls https://coverage.codacy.com/get.sh)
}

run_frontend_check(){
  cd frontend
  pnpm install --no-frozen-lockfile
  pnpm lint
  pnpm coverage
  pnpm build
  bash <(curl -Ls https://coverage.codacy.com/get.sh)
}

if [[ "$#" -le 0 ]]; then
  display_help
  exit 0
fi

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -h|--help) display_help; shift ;;
        frontend) run_frontend_check ;;
        backend) run_backend_check ;;
        *) echo "Unknown parameter passed: $1" ;;
    esac
    shift
done
