env:
  RETENTION_DAYS: "10"

steps:
  - label: ":white_check_mark: Check Shell"
    key: "check-shell"
    command: ./ops/check.sh shell

  - label: ":lock: Check Security"
    key: "check-security"
    command: ./ops/check.sh security

  - label: ":lock: Check CSS px"
    key: "check-px"
    command: ./ops/check.sh px

  - label: ":lock: Deny CSS hex"
    key: "deny-css-hex-check"
    command: ./ops/check.sh hex

  - label: ":lock: Deny CSS rgba"
    key: "deny-css-rgba-check"
    command: ./ops/check.sh rgba

  - label: ":lock: Check .* in backend"
    key: "check-dot-star"
    command: ./ops/check.sh dot-star

  - label: ":white_check_mark: Check Backend"
    if: build.branch == "main" && build.message =~ /(?i)\[backend\]/
    key: "check-backend"
    command: ./ops/check.sh backend

  - label: ":white_check_mark: Check Frontend"
    if: build.branch == "main" && build.message =~ /(?i)\[frontend\]/
    key: "check-frontend"
    command: ./ops/check.sh frontend

  - label: ":mag: Check Frontend License"
    key: "check-frontend-license"
    commands: ./ops/check.sh frontend-license

  - label: ":mag: Check Backend License"
    key: "check-backend-license"
    commands: ./ops/check.sh backend-license
    plugins:
      - artifacts#v1.9.0:
          upload:
            - "backend/build/reports/dependency-license/**/*"
          name: "backend-license-report"
          expire_in: "${RETENTION_DAYS} days"

  - label: ":cloudformation: Deploy infra"
    if: build.branch == "main" && build.message =~ /(?i)\[infra\]/
    key: "deploy-infra"
    depends_on:
      - "check-shell"
      - "check-security"
      - "check-frontend"
      - "check-px"
      - deny-css-rgba-check
      - deny-css-hex-check
      - "check-backend"
      - "check-frontend-license"
      - "check-backend-license"
    env:
      AWSHost: "$AWS_HOST"
      AWSAccountId: "$AWS_ACCOUNT_ID"
      AWSRegion: "$AWS_REGION"
    command: ./ops/deploy.sh infra

  - label: ":react: Build Frontend"
    if: build.branch == "main" && build.message =~ /(?i)\[frontend\]/
    key: "build-frontend"
    depends_on: "deploy-infra"
    command: ./ops/build.sh frontend

  - label: ":java: Build Backend"
    if: build.branch == "main" && build.message =~ /(?i)\[backend\]/
    key: "build-backend"
    depends_on: "deploy-infra"
    command: ./ops/build.sh backend

  - label: ":rocket: Deploy e2e"
    if: build.branch == "main" && (build.message =~ /(?i)\[frontend\]/ || build.message =~ /(?i)\[backend\]/)
    key: "deploy-e2e"
    depends_on:
      - "build-frontend"
      - "build-backend"
    command: ./ops/deploy.sh e2e

  - label: ":rocket: Run e2e"
    branches: main
    key: "check-e2e"
    depends_on:
      - "deploy-e2e"
      - "check-shell"
      - "check-security"
      - "check-frontend"
      - "check-px"
      - deny-css-rgba-check
      - deny-css-hex-check
      - "check-backend"
      - "check-frontend-license"
      - "check-backend-license"
    command: ./ops/check.sh e2e-container
    plugins:
      - artifacts#v1.9.0:
          upload: "./e2e-reports.tar.gz"
          expire_in: "${RETENTION_DAYS} days"

  - label: ":rocket: Deploy prod"
    if: build.branch == "main" && (build.message =~ /(?i)\[frontend\]/ || build.message =~ /(?i)\[backend\]/)
    depends_on:
      - "check-e2e"
    command: ./ops/deploy.sh prod
