env:
  RETENTION_DAYS: "10"

steps:
  - label: ":cloudformation: Deploy infra"
    if: build.branch == "main" && build.message =~ /(?i)\[infra\]/
    key: "deploy-infra"
    env:
      AWSHost: "$AWS_HOST"
      AWSAccountId: "$AWS_ACCOUNT_ID"
      AWSRegion: "$AWS_REGION"
    command: ./ops/deploy.sh infra

  - label: ":white_check_mark: GitHub Basic Check"
    if: build.branch == "main"
    key: "check-github-basic"
    command: ./ops/check.sh github-basic-passed
    env:
      COMMIT_SHA: "$BUILDKITE_COMMIT"
      GITHUB_TOKEN: "$E2E_TOKEN_GITHUB"
      BRANCH: "$BUILDKITE_BRANCH"
    depends_on:
      - "deploy-infra"

  - label: ":react: Build Frontend"
    if: build.branch == "main" && build.message =~ /(?i)\[frontend\]/
    key: "build-frontend"
    depends_on:
      - "check-github-basic"
    command: ./ops/build.sh frontend

  - label: ":java: Build Backend"
    if: build.branch == "main" && build.message =~ /(?i)\[backend\]/
    key: "build-backend"
    depends_on:
      - "check-github-basic"
    command: ./ops/build.sh backend

  - label: ":rocket: Deploy e2e"
    if: build.branch == "main"
    key: "deploy-e2e"
    depends_on:
      - "build-frontend"
      - "build-backend"
      - "check-github-basic"
    command: ./ops/deploy.sh e2e

  - label: ":rocket: Run e2e"
    if: build.branch == "main"
    key: "check-e2e"
    depends_on:
      - "deploy-e2e"
    command: ./ops/check.sh e2e-container
    plugins:
      - artifacts#v1.9.3:
          upload: "./e2e-reports.tar.gz"
          expire_in: "${RETENTION_DAYS} days"

  - label: ":rocket: Deploy prod"
    if: build.branch == "main" && (build.message =~ /(?i)\[frontend\]/ || build.message =~ /(?i)\[backend\]/)
    depends_on:
      - "check-e2e"
    command: ./ops/deploy.sh prod
