FROM mcr.microsoft.com/playwright
COPY ./frontend /app

ENV TZ=Asia/Shanghai
ENV PATH /app/node_modules/.bin:$PATH
WORKDIR /app
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile -p
RUN pnpm exec playwright install
RUN pnpm exec playwright install msedge
RUN pnpm exec playwright install chrome
