name: Bug Report
description: Report a bug to Heartbeat
title: "[Bug] "
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      The issue list is reserved exclusively for bug reports and feature requests.

      For usage questions, please use the following resources:

      - Read the [docs](https://au-heartbeat.github.io/Heartbeat)

      For non-technical support or general questions, you can email [heartbeat-dev@thoughtworks.com](mailto:heartbeat-dev@thoughtworks.com).

      Also try to search your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue using the form below instead of commenting on the old issue.

      Last please double confirm that you had already verified it can be replicated in the latest version, otherwise use the latest stable version could be the fastest way to resolve your issue.

- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com or full name that we can connect you in Slack or WeCom
  validations:
    required: true

- type: input
  id: version
  attributes:
    label: Version
    description: |
      What version of our software are you running? There is two methods to get the current version:
        1. you can see the version info at the left top of the heartbeat pages
        2. If you could not get the version, you can input "1.0.0" as well
  validations:
    required: true

- type: dropdown
  id: browsers
  attributes:
    label: What browsers are you seeing the problem on?
    multiple: true
    options:
      - Firefox
      - Chrome
      - Safari
      - Microsoft Edge

- type: dropdown
  id: page
  attributes:
    label: Pages
    description: Which page you met this issue in?
    multiple: true
    options:
      - Config
      - Metrics
      - Report
    default: 0
  validations:
    required: true

- type: dropdown
  id: tool
  attributes:
    label: Tools
    description: What tools your issue is related to?
    multiple: true
    options:
      - Board
      - Pipeline Tool
      - Source Control
  validations:
    required: true

- type: textarea
  attributes:
    label: Summary
    description: |
      Please give us some info about your bug.
    placeholder: |
      1. I want to get the metrics report, but failed.
      2. ......
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to Reproduce
    description: |
      What do we need to do after opening your repo in order to make the bug happen? Clear and concise reproduction instructions are important for us to be able to triage your issue in a timely manner. Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format lists and code.
    placeholder: |
      1. What's you input? Mask sensitive data
      2. What's you select?
      3. ......
  validations:
    required: true

- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing and upload the screenshots.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Any additional comments?
    description: |
      e.g. some background/context of how you ran into this bug.
  validations:
    required: false
