#!/bin/bash
set -euo pipefail

display_help() {
    echo "Usage: $0 {frontend|backend|mockserver}" >&2
    echo
    echo "   frontend     build frontend"
    echo "   backend      build backend"
    echo "   mockserver   build mockserver"
    echo
    exit 1
}

build_backend() {
    # aws configure set region $AWS_REGION
    # eval $(aws sts assume-role --role-arn $AWS_GITHUB_ACTION_ROLE --role-session-name buildkite | jq -r '.Credentials | to_entries | map(.key + "=" + "\"" + (.value | tostring) + "\"") | .[]')
    # aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
    # echo "start to build backend 11"
    # docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:latest ./ -f ./infra/Dockerfile.backend
    # echo "start to build backend 22"
    # docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:hb${BUILDKITE_BUILD_NUMBER} ./ -f ./infra/Dockerfile.backend
    # docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:latest
    # docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:hb${BUILDKITE_BUILD_NUMBER}
    # docker rmi $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:latest
    # docker rmi $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:hb${BUILDKITE_BUILD_NUMBER}
    export PATH="$PATH:~/bin/trivy"
    echo "trivy version"
    trivy --version
    ~/bin/trivy image --severity HIGH,CRITICAL --exit-code 1 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:latest
}

build_mockserver() {
    echo "build mockserver"
}

build_frontend() {
    echo "build frontend"
}



if [[ "$#" -le 0 ]]; then
  display_help
fi

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -h|--help) display_help ;;
        frontend) build_frontend ;;
        backend) build_backend ;;
        mockserver) build_mockserver ;;
        *) echo "Unknown parameter passed: $1" ;;
    esac
    shift
done
