#!/bin/bash
set -e
set +x

display_help() {
    echo "Usage: $0 {infra|e2e|stub}" >&2
    echo
    echo "   infra    deploy infra"
    echo "   ec2      deploy ec2"
    echo "   stub     deploy stub"
    echo
    exit 1
}
deploy_infra(){

}

deploy_ec2(){

}

deploy_stub(){

}

if [[ "$#" -le 0 ]]; then
  display_help
  exit 0
fi

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -h|--help) display_help; shift ;;
        infra) deploy_infra ;;
        ec2) deploy_ec2 ;;
        backend) backend_check ;;
        stub) deploy_stub ;;
        deploy) deploy ;;
        *) echo "Unknown parameter passed: $1" ;;
    esac
    shift
done