#!/bin/bash

# The `pre-exit` hook will run just before your build job finishes

# Note that as the script is sourced not run directly, the shebang line will be ignored
# See https://buildkite.com/docs/agent/v3/hooks#creating-hook-scripts

set -euo pipefail

echo "Start to perform cleanup"

rm -rf /var/lib/buildkite-agent/builds/*
rm -rf /var/lib/buildkite-agent/.cache/*
rm -rf /var/lib/buildkite-agent/.local/*

docker system df
docker system prune -a --volumes --force

echo "Finished to perform cleanup"
