#!/bin/bash
set +x
run_backend_check() {
  echo "--- Test and check"
  ./gradlew clean check
  echo "--- Build"
  ./gradlew clean build
  # echo "--- Uploading Test Report to Codacy"
  # docker run --rm -v "$PWD/backend":/coverage -w /coverage codacy/coverage-reporter:latest report -l Java -r build/reports/tests/test/index.html --projectToken $CODACY_PROJECT_TOKEN
}
run_backend_check