#!/bin/bash
set +x
run_backend_check() {
  # docker run --rm -v "$PWD/backend":/home/gradle/project -v /var/cache/gradle:/home/gradle/.gradle -w /home/gradle/project gradle:8-jdk17-alpine gradle clean check
  cd backend
  echo "--- Check"
  ./gradlew clean check
  echo "--- Build "
  ./gradlew clean build
  echo "--- Uploading Test Report to Codacy"
  bash <(curl -Ls https://coverage.codacy.com/get.sh)
  # docker run --rm -v "$PWD/backend":/coverage -w /coverage codacy/coverage-reporter:latest report -l Java -r build/reports/tests/test/index.html --projectToken $CODACY_PROJECT_TOKEN
}
run_backend_check